# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: saikou-api
  password: 

development:
  <<: *default
  database: saikou-api_development

test:
  <<: *default
  database: saikou-api_test

production:
  <<: *default
  database: saikou-api_production